__import__ (script): configs.scripts.running

runner: !diffusionism.runner.DiffusionRunner
  data_getter: script.data_getter
  target_data_getter: script.target_data_getter
  source_data_getter: script.source_data_getter
  initial_state_getter: script.initial_state_getter
  initial_noise_strength: 0.8
  metrics: !monai.metrics.SSIMMetric
    spatial_dims: 2
    data_range: 1.
    win_size: 7