__import__ (script): configs.scripts.running

runner: !?diffusionism.runner.generative.diffusion.DiffusionRunner
  target_data_getter: script.target_data_getter
  source_data_getter: script.source_data_getter
  data_getter: script.data_getter
  initial_state_getter: script.initial_state_getter
  initial_noise_strength: 1.0
  metrics:
    - !monai.metrics.PSNRMetric
        max_val: 1.
    - !monai.metrics.SSIMMetric
        spatial_dims: 2
        data_range: 1.
        win_size: 7