settings:
  devices: ['cuda:0']
  checkpoint_path: 
  precision: 'bf16-mixed'
  output_root: './sampled_images'
  
test_data_loader: !torch.utils.data.DataLoader
  batch_size: 48
  shuffle: False
  num_workers: 4
  dataset: !diffusionism.utils.dataset.RandomDataset
    dataset: 