settings:
  devices: [0]
  monitor: 'SSIMMetric'
  val_epoch_interval: 1
  val_step_interval: null
  saving_epoch_interval: 1
  saving_step_interval: null
  max_epochs: &epochs 200
  precision: 'bf16-mixed'
  grad_clip_norm: 1.
  weight_path: null

optimizer: &optim !?torch.optim.AdamW
  lr: 5.e-4
  weight_decay: 1.e-4
  betas: [0.9, 0.95]
  eps: 1.e-8

lr_scheduler: !?diffusionism.utils.lr_scheduler.GradualWarmupScheduler
  multiplier: 1.
  max_epochs: *epochs
  after_scheduler: !?torch.optim.lr_scheduler.CosineAnnealingLR
    T_max: *epochs
    eta_min: 0
    last_epoch: -1

train_data_loader: !torch.utils.data.DataLoader
  batch_size: 48
  shuffle: True
  num_workers: 4
  dataset: # Insert the dataset initialization.